### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by Vilicky** [NachoMarrero/PROYECTO_FINAL#2]
Hola @natydasilva @fedemolina como estan?
Me di cuenta de que habíamos cometido un error al incluir la superficie en hectáreas porque me daban cosas raras y consulté las hectáreas deberían corregirse por calidad de suelo (con la variable b5, que es el índice Conneat). Cuando fui a realizar la correción me encontré con varios datos que tenían 0 y para no asumir ningún valor preferí filtrarlos. Ahora cuando voy a graficar con esta nueva variable que sería la tierra corregida por calidad el gráfico no me funciona bien, me podrán dar alguna ayuda? Gracias!

datos %>% 
  group_by(b5,b3_7,est) %>% 
  filter(b5!=0) %>% 
  summarise(a=b5*b3_7/100)%>%
  mutate(a = case_when(a %in% c(0:200)  ~ "0-200",
                          a %in% c(201:400)  ~ "200-400",
                          a %in% c(401:600)  ~ "400-600",
                          a > 600 ~ "600")) %>%
  ggplot() +
  geom_mosaic(aes(x = product(a, est), fill= a))+
  scale_fill_brewer(palette = "Set2")+
  theme_bw()

**Comment by fedemolina** [comment]
Buenas, pudieron solucionar? Dónde esta ese código no lo veo en el proyecto.rmd
